---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flagger
  namespace: istio-system
spec:
  releaseName: flagger
  chart:
    repository: https://flagger.app
    name: flagger
    version: 0.27.0
  values:
    metricsServer: "http://prometheus:9090"
    meshProvider: "istio"
    # slack:
    #   user: flagger
    #   channel:
    #   # incoming webhook https://api.slack.com/incoming-webhooks
    #   url:
