---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flagger-loadtester
  namespace: istio-system
spec:
  releaseName: flagger-loadtester
  chart:
    repository: https://flagger.app
    name: loadtester
    version: 0.16.0
