---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: loki
spec:
  values:
    loki:
      enabled: true
      serviceMonitor:
        enabled: true
        interval: "15s"
    promtail:
      enabled: true
      serviceMonitor:
        enabled: true
        interval: "15s"
    fluent-bit:
      enabled: false
    grafana:
      enabled: false
    prometheus:
      enabled: false
