---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-additional-datasources
  labels:
    grafana_datasource: "1"
type: Opaque
stringData:
  datasource.yaml: |-
    # config file version
    apiVersion: 1

    datasources:
    - name: Thanos
      type: prometheus
      access: proxy
      orgId: 1
      url: http://thanos-query-http:10902
      isDefault: true
    - name: Prometheus
      type: prometheus
      access: proxy
      orgId: 1
      url: http://prometheus-operator-prometheus:9090
    - name: Loki
      type: Loki
      access: proxy
      orgId: 1
      url: http://loki:3100
    - name: Jaeger
      type: Jaeger
      access: proxy
      orgId: 1
      url: http://jaeger-operator-jaeger-query:16686
