namespace: observability
resources:
- namespace.yaml
- grafana-secret.yaml
- grafana-additional-datasources.yaml
bases:
- ../base/prometheus-operator
- ../base/thanos
- ../base/grafana-loki
- ../base/jaeger-operator
patchesStrategicMerge:
- prometheus-operator-patch.yaml
- thanos-patch.yaml
- grafana-loki-patch.yaml
- jaeger-operator-patch.yaml
