---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-operator
spec:
  values:
    alertmanager:
      alertmanagerSpec:
        image:
          tag: v0.20.0
        replicas: 1
    grafana:
      admin:
        existingSecret: grafana
        userKey: admin-user
        passwordKey: admin-password
      image:
        tag: 7.0.3
      sidecar:
        datasources:
          enabled: false
          defaultDatasourceEnabled: false
    prometheus:
      prometheusSpec:
        scrapeInterval: 15s
        scrapeTimeout: 10s
        evaluationInterval: 15s
        retention: 6h
        image:
          tag: v2.18.1
        replicas: 1
        remoteWriteDashboards: false
        thanos:
          baseImage: quay.io/thanos/thanos
          version: v0.12.2
    kubeEtcd:
      enabled: false
    kubeProxy:
      enabled: false
