---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-operator
spec:
  values:
    alertmanager:
      alertmanagerSpec:
        image:
          tag: v0.20.0
        replicas: 1
    grafana:
      admin:
        existingSecret: grafana
        userKey: admin-user
        passwordKey: admin-password
      image:
        tag: 7.0.3
      sidecar:
        datasources:
          defaultDatasourceEnabled: false
          createPrometheusReplicasDatasources: false
      additionalDataSources:
        - name: Thanos
          type: prometheus
          orgId: 1
          access: proxy
          url: http://thanos-query-http:10902
          isDefault: true
        - name: Prometheus
          type: prometheus
          orgId: 1
          access: proxy
          url: http://prometheus-operated:9090
        - name: Loki
          type: Loki
          orgId: 1
          access: proxy
          url: http://loki:3100
        - name: Jaeger
          type: Jaeger
          orgId: 1
          access: proxy
          url: http://jaeger-operator-jaeger-query:16686
    prometheus:
      prometheusSpec:
        scrapeInterval: 15s
        scrapeTimeout: 10s
        evaluationInterval: 15s
        retention: 6h
        image:
          tag: v2.18.1
        replicas: 1
        remoteWriteDashboards: false
        thanos:
          baseImage: quay.io/thanos/thanos
          version: v0.12.2
    kubeEtcd:
      enabled: false
    kubeProxy:
      enabled: false
