---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: thanos
spec:
  values:
    image:
      repository: quay.io/thanos/thanos
      tag: v0.12.2
      pullPolicy: IfNotPresent

    store:
      enabled: false

    query:
      enabled: true
      # Label to treat as a replica indicator along which data is deduplicated.
      # Still you will be able to query without deduplication using
      # 'dedup=false' parameter.
      replicaLabel: "prometheus_replica"
      replicaCount: 1
      # Addresses of statically configured store API servers (repeatable).
      # The scheme may be prefixed with 'dns+' or 'dnssrv+' to detect store
      # API servers through respective DNS lookups.
      stores:
        - "dnssrv+_grpc._tcp.prometheus-operated.observability.svc.cluster.local"
      # Enable metrics collecting for query service
      metrics:
        # Enable ServiceMonitor https://github.com/coreos/prometheus-operator
        serviceMonitor:
          enabled: true
          labels:
            release: prometheus-operator

    compact:
      enabled: false

    bucket:
      enabled: false

    rule:
      enabled: false

    sidecar:
      # NOTE: This is only the service references for the sidecar
      enabled: false

    # This is the general backend configuration. Please se the examples below
    # to configurate object store.
    # More information can be found at thanos github repositoriy:
    # https://github.com/thanos-io/thanos/blob/master/docs/storage.md
    # Existing secret containing the configuration.
    # The key must be `object-store.yaml`
    objstoreSecretOverride: ""
    # Text representation of the configuration
    objstoreFile: ""
    # YAML representation of the configuration.
    # It's mutually exclusive with objstoreFile.
    objstore: {}
