on: [push, pull_request]
name: test
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate kustomization
        uses: stefanprodan/kube-tools@v1
        with:
          # https://github.com/fluxcd/flux/blob/master/docker/kubectl.version
          kubectl: 1.14.7
          # https://github.com/fluxcd/flux/blob/master/docker/kustomize.version
          kustomize: 3.4.0
          # https://github.com/fluxcd/helm-operator/blob/master/docker/helm.version
          helm: 2.14.3
          command: |
            echo "Validating flagger"
            kustomize build manifests/flagger | kubeval --strict --ignore-missing-schemas
